### ISSUE TITLE
Project Updates

### ISSUE THREAD

**Issue by JasonBock** [JasonBock/Transpire#25]
## Tasks
* [x] Add a changelog file
* [x] Use central package management
* [x] Update .csproj file with relevant settings to include README, CHANGELOG, and anything else relevant.
* [x] Update package references
* [x] Create an icon
* [x] Remove the VSIX project and change `Transpire.Vsix.Scenarios` to just `Transpire.Scenarios`. This project should reference `Transpire` as an analyzer project.
* [x] Change literal strings to raw strings, especially in the tests.
